const data = [ 
    {
        "name": "Sun",
        "link": "https://en.wikipedia.org/wiki/Sun",
        "size": "1.3*10<sup>6</sup> km",
        "distance": "0 km",
        "orbit": "N/A",
        "rotation": "27 days",
        "gases": "H, He",
        "gravity":"274",
        "temperature": "5726&degC",
        "img":"./assets/sun.png",
    },
    {
        "name": "Mercury",
        "link": "https://en.wikipedia.org/wiki/Mercury_(planet)",
        "size": "4,880 km",
        "distance": "65.147 Million km",
        "orbit": "88 days",
        "rotation": "56 days",
        "gases": "N/A",
        "gravity":"3.7",
        "temperature": "-173&degC - 420&degC",
        "img":"./assets/mercury.png"
    },
    {
        "name": "Venus",
        "link": "https://en.wikipedia.org/wiki/Venus",
        "size": "12,100 km",
        "distance": "108.75 Million km",
        "orbit": "225 days",
        "rotation": "243 days",
        "gases": "CO2, N",
        "gravity":"8.87",
        "temperature": "460&degC",
        "img":"./assets/venus.png"
    },
    {
        "name": "Earth",
        "link": "https://en.wikipedia.org/wiki/Earth",
        "size": "12,700 km",
        "distance": "150.11 Million km",
        "orbit": "365 days",
        "rotation": "24 hours",
        "gases": "N, O, CO2",
        "gravity":"9.8",
        "temperature": "14&degC",
        "img":"./assets/earth.png"
    },
    {
        "name": "Mars",
        "link": "https://en.wikipedia.org/wiki/Mars",
        "size": "6,800 km",
        "distance": "228 Million km",
        "orbit": "687 days",
        "rotation": "24.6 hours",
        "gases": "CO2, N, Ar",
        "gravity":"3.7",
        "temperature": "-64&degC",
        "img":"./assets/mars.png"
    },
    {
        "name":"Jupiter",
        "link": "https://en.wikipedia.org/wiki/Jupiter",
        "size":"142,984 km",
        "distance": "778 Million km",
        "orbit":"12 years",
        "rotation":"10 hours",
        "gases":"H, He",
        "gravity":"22.9",
        "temperature": "-121&degC",
        "img":"./assets/jupiter.png"
    },
    {
        "name": "Saturn",
        "link": "https://en.wikipedia.org/wiki/Saturn",
        "size": "116,464 km",
        "orbit": "29.4 years",
        "distance": "1.451 Billion km",
        "rotation": "10.7 hours",
        "gases": "H, He, CH4, NH3",
        "gravity":"10.4",
        "temperature": "-138&degC",
        "img":"./assets/saturn.png"
    },
    {
        "name": "Uranus",
        "link": "https://en.wikipedia.org/wiki/Uranus",
        "size": "50,724 km",
        "orbit": "84 years",
        "distance": "2.9304 Billion km",
        "rotation": "17 hours",
        "gases": "H, He, CH4, H2O, NH3",
        "gravity":"8.87",
        "temperature": "-220&degC",
        "img":"./assets/uranus.png"
    },
    {
        "name": "Neptune",
        "link": "https://en.wikipedia.org/wiki/Neptune",
        "size": "49,528 km",
        "orbit": "164 years",
        "distance": "4.4722 Billion km",
        "rotation": "16 hours",
        "gases": "H, He, CH4",
        "gravity":"11.15",
        "temperature": "-232&degC",
        "img":"./assets/neptune.png"
    }
    
]